### ISSUE TITLE
[CKEDITOR] Error code: editor-destroy-iframe. 

### ISSUE THREAD

**Issue by deep3092** [chymz/ng2-ckeditor#212] opened 2018-04-13 14:11 UTC
I need help. is there any plugin required to overcome this console error . i'm using ng2 ckeditor
ckeditor version: full(4.9.0)
angular 5.2.8

**Comment by p3t3r5** [comment] 2018-04-13 15:25
I have the same problem. I think, the problem is destroy of CKEditor Instance in setTimeout(). Parent components are destroyed before CKEditor is destroyed.

**Comment by p3t3r5** [comment] 2018-04-14 04:31
Why? Workaround? My be, but crazy.... 2 hours of frustration.   NGX?

**Comment by kzimny** [comment] 2018-04-14 06:29
Maybe you are right. But function setTimeout() without optional parameter in millisecond execute the code immediately. Let ask @chymz : why are you using setTimeout() function? On the other hand, how does your application use ng2-ckeditor? How can you be helped if you do not provide more information about your application. Without any code the chance to help is very low? A plunker would be very helpful.

**Comment by deep3092** [comment] 2018-04-16 15:56
so there is no proper solution ? please help

**Comment by chymz** [comment] 2018-04-16 16:15
There is a link in README : https://github.com/chymz/ng2-ckeditor/issues/24

If you use CKEditor in normal mode, it will create an Iframe to display its content. In this case ngOnDestory is running before this iframe is destroyed, and then display this error.

There is only one solution, use the divarea plugin: https://ckeditor.com/cke4/addon/divarea

**Comment by kzimny** [comment] 2018-10-03 14:19
@vikrantpogula : I don't belive that the "before destroy" event will ever be realized in angular. Did you hear something else? I propose to close the issue.

**Comment by vikrantpogula** [comment] 2018-10-08 15:47
@kzimny yes you are correct.. maybe in angular 7 or further. I have worked around this with manual destroys

**Comment by kzimny** [comment] 2018-10-08 18:00
Look at this [comment](https://github.com/chymz/ng2-ckeditor/issues/24#issuecomment-427493276). Maybe it is what you are looking for.

**Closed by kzimny** 2018-10-08 18:00 UTC
